name: CI

on:
  pull_request:
  push:
    branches-ignore: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: 'pityka/base-ubuntu-libtorch-sbt:torch20'
      env: 
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0    
    - name: Compile
      run: sbt -mem 3000 clean +test docs/mdoc docs/unidoc