name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: 'pityka/base-ubuntu-libtorch:torch171'
      env: 
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
    
    steps:
    - uses: actions/checkout@v1
    - name: Compile
      run: sbt -mem 3000 clean coverage test coverageAggregate
    - name: Codecov
      uses: codecov/codecov-action@v1.0.15
      if: github.actor == 'pityka'
      with:
        token: ${{secrets.CODECOV_TOKEN}}