name: master

on:
  push:
    branches: [master]
    tags: ["*"]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: 'pityka/base-ubuntu-libtorch-sbt:torch1121'
      env: 
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0   
    - name: install git
      run: apt-get update && apt-get install -y git    
    - name: Compile
      run: sbt version